name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HOME_PATH: ${{ github.workspace }}
  SOURCE_PATH: src
  TEST_PATH: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Korn shell
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install ksh

      - name: Install Newman
        shell: bash
        run: |
          npm install -g newman

      - name: Build
        shell: bash
        run: |
          cd ${HOME_PATH}
          ./build.sh dependencies compile

      - name: Unit Tests
        shell: bash
        run: |
          cd ${HOME_PATH}
          ./build.sh test

      - name: Integration Tests
        shell: bash
        run: |
          cd ${HOME_PATH}
          ./build.sh verify
